version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  build:
    commands:
       - mvn package

artifacts:
  files:
     - 'target/*.jar'
   name: petclinic-$(CODEBUILD_SOURCE_VERSION)

cache:
  paths:
    - '/root/.m2/**/*'
